# Generated by Django 3.1.2 on 2021-07-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0022_sale_every_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='every_day',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_frequency',
            field=models.CharField(choices=[('minute', 'minute'), ('hour', 'hour'), ('day', 'day')], default='day', max_length=10, verbose_name='Как часто изменять стоимость'),
        ),
        migrations.AddField(
            model_name='sale',
            name='value_frequency',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
