# Generated by Django 3.1.2 on 2021-07-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0024_sale_periodically_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount_frequency',
        ),
        migrations.AddField(
            model_name='sale',
            name='value_discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
