# Generated by Django 3.1.2 on 2021-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_auto_20200810_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_entity',
            field=models.BooleanField(default=False),
        ),
    ]
