# Generated by Django 3.1.2 on 2021-07-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_user_is_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_entity',
        ),
    ]
